name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1
      with:
        otp-version: '22.3'
        elixir-version: '1.9'
    - name: Run elasticmq
      run: docker run -d -p 9324:9324 softwaremill/elasticmq
    - run: mix deps.get
    - run: mix test --include external:true
